const fs = require('fs')
const path = require('path')
console.log(new Date())
const year = new Date().getFullYear()
const month = new Date().getMonth()
const date = new Date().getDate()
console.log(year)