const fs = require('fs')
const path = require('path')
console.log(new Date())
const year = new Date().getFullYear()
const year = new Date().getFullYear()
const year = new Date().getFullYear()
const year = new Date().getFullYear()
const year = new Date().getFullYear()
console.log(year)